### ISSUE TITLE
Questions regrading results on Han et al.(2019)

### ISSUE THREAD

**Issue by Chung-I** [WinnieHAN/mndmv#1]
Hi authors, thanks for sharing the code for the paper! (especially the Eisner's algorithm for DMV, which is perhaps the most difficult part ... )
I have a few questions, though, on reproducing the result on the paper:
1. How did you select models? Did you use any gold parse throughout the experiment? e.g.  based on validation UAS?
2. Is it the following command that reproduces G and G+I result in Table 3?
```
python ml_dmv_parser.py --cvalency 2 --do_eval --neural_epoch 1 --function_mask --lr 0.001 --epoch 70 --use_neural --embed_languages --em_type em --child_only --sentence_predict
```

Thank you so much!

**Comment by mikufan** [comment]
Sorry for late response, we're just too busy these days.
The first question, as we're dealing with a multilingual task, I'm not sure if validation UAS  is a good choice, I think it is ok to just pick the model that producing the highest training likelihood when it converges for the unsupervised learning scenario.
The second question, the command should produce the G+I results, if you want G results,turn off the last option

**Comment by Chung-I** [comment]
1. I totally agree with you. Results obtained by choosing models with validation UAS are just not fully unsupervised in the strictest sense.
2. I see.
Thanks for the response! I'll close this issue.
